### ISSUE TITLE
Atom 0.189 plugin stylesheets check

### ISSUE THREAD

**Issue by arturparkhisenko** [d4rkr00t/css-comb-atom#10]
Store package style sheets in the styles/ directory instead of stylesheets/ in the atom-css-comb package

Called 6 times

Package.getStylesheetsPath - C:\Users\Administrator\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:448:9
Package.getStylesheetPaths - C:\Users\Administrator\AppData\Local\atom\app-0.189.0\resources\app\src\package.js:459:32

**Comment by d4rkr00t** [comment]
Wow, thanks, i'll fix it

**Comment by d4rkr00t** [comment]
Hm, sorry, what styles do you have in css-comb package? Do you use this https://atom.io/packages/css-comb package or this one https://atom.io/packages/atom-css-comb ? Because i don't have any styles in my package.

**Comment by arturparkhisenko** [comment]
Ow, yes. sorry, i found css-comb-atom but i need post it on https://github.com/jchouse/csscomb-atom
Thank you!
