### ISSUE TITLE
When trying to use comb with ctr+opt+c, there's an error popup

### ISSUE THREAD

**Issue by vesakilp** [d4rkr00t/css-comb-atom#113]
Error popup message:

Please check the validity of the block starting from line #undefined
Gonzales PE version: 3.0.0-28 Syntax: undefined

Atom version: 1.17.2

**Comment by d4rkr00t** [comment]
Hm, I've seen that before, it happens when you select something that parser of css-comb doesn't understand as complete css block

**Comment by vesakilp** [comment]
Yeah, I didn't actually have anything selected, thought that it would mean that the whole document gets combed. But you have to select all for that.
