### ISSUE TITLE
Support csscomb.cson

### ISSUE THREAD

**Issue by danielbayley** [d4rkr00t/css-comb-atom#14]

**Comment by d4rkr00t** [comment]
Hi. Any use cases? 

I think css-comb-atom should support only those formats for configs which are supported by csscomb itself. And I don't want to introduce extra complexity to config search/load logic.

**Comment by danielbayley** [comment]
Hey, well I suggested this as another CSScomb package ([bruce/atom-csscomb](https://github.com/bruce/atom-csscomb/blob/master/lib/csscomb.coffee#L18)) has this feature but otherwise doesn't work as nicely as yours.

The use case is simply being able to write what is yet _another_ config file in CSON instead of JSON (eww...)

Although I am actually using CSScomb through atom-beautify now instead…

**Comment by d4rkr00t** [comment]
Sorry I'm closing this issue.
