### ISSUE TITLE
On Save Option

### ISSUE THREAD

**Issue by JosefJezek** [d4rkr00t/css-comb-atom#3]
Could you add On Save Option?

Like this package
https://github.com/lee-dohm/tabs-to-spaces

**Comment by d4rkr00t** [comment]
Hi, why not, I'll do it :)

**Comment by d4rkr00t** [comment]
Closed via https://github.com/d4rkr00t/css-comb-atom/commit/4ccc35054a464726b274b63ec3fa2cd1667b70a8
