### ISSUE TITLE
No excluding files on save

### ISSUE THREAD

**Issue by nielsenramon** [d4rkr00t/css-comb-atom#46]
I am trying to exclude a file (normalize.scss) from combing on save but I can't get it to work. I tries absolute paths and relative ones but nothing seems to work. 

The `.csscomb.json` file is in my stylesheets folder and `generic/_normalize.scss` is in there as well.

In my config I have the following line:

```
"exclude": ["generic/**"],
```

Any idea how to fix this?

Thanks!

**Comment by d4rkr00t** [comment]
Hi, does it work when running csscomb from terminal?

**Comment by d4rkr00t** [comment]
Hi, 
I guess it's happening because plugin provides file content to csscomb instead of file path here https://github.com/d4rkr00t/css-comb-atom/blob/master/src/css-comb.js#L73

I'll take a look at this issue at weekends.

**Comment by nielsenramon** [comment]
@d4rkr00t Alright thanks man!

**Comment by d4rkr00t** [comment]
Should work now :)

**Comment by nielsenramon** [comment]
@d4rkr00t Hmm I can't get it to work on my client. Latest version. Even re-installed your package. Keeps executing in that folder. Anything wrong on my side? How does the package check the path?

**Comment by d4rkr00t** [comment]
Hi, it checks relative to root directory, where atom is opened.

I'll recheck it again, maybe i messed something up :)

**Comment by d4rkr00t** [comment]
@nielsenramon Oh, I see from original description that .csscomb.json is in stylesheets folder, so I have to rewrite exclude logic a bit to make it work.

**Comment by d4rkr00t** [comment]
I think you can write exclude path relative to the root folder and it should work. 

```
"exclude": ["stylesheets/generic/**"],
```

And I'll fix it in few days :)

**Comment by nielsenramon** [comment]
@d4rkr00t Indeed I had to use the path relative to the root 👍 Thanks!
You could indeed build it so the excluded files are relative to the `.csscomb.json` file location but it's already awesome I no longer have to disable the plugin just for the exluded files ⭐

**Comment by d4rkr00t** [comment]
Yep, I'll do it :)

**Comment by d4rkr00t** [comment]
Second attempt :) 

@nielsenramon  Can you check it please?

**Comment by nielsenramon** [comment]
@d4rkr00t Awesome it works great! Thanks for the effort man :)

**Comment by d4rkr00t** [comment]
Thanks for bug report!
